/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleSejaUmParceiroIndexRouteImport } from './routes/$locale/seja-um-parceiro/index'
import { Route as LocaleQueroAjudarIndexRouteImport } from './routes/$locale/quero-ajudar/index'
import { Route as LocaleComoFuncionaIndexRouteImport } from './routes/$locale/como-funciona/index'
import { Route as LocaleAppIndexRouteImport } from './routes/$locale/app/index'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSejaUmParceiroIndexRoute =
  LocaleSejaUmParceiroIndexRouteImport.update({
    id: '/seja-um-parceiro/',
    path: '/seja-um-parceiro/',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleQueroAjudarIndexRoute = LocaleQueroAjudarIndexRouteImport.update({
  id: '/quero-ajudar/',
  path: '/quero-ajudar/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleComoFuncionaIndexRoute = LocaleComoFuncionaIndexRouteImport.update({
  id: '/como-funciona/',
  path: '/como-funciona/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAppIndexRoute = LocaleAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => LocaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/app': typeof AppRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/app/': typeof LocaleAppIndexRoute
  '/$locale/como-funciona/': typeof LocaleComoFuncionaIndexRoute
  '/$locale/quero-ajudar/': typeof LocaleQueroAjudarIndexRoute
  '/$locale/seja-um-parceiro/': typeof LocaleSejaUmParceiroIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/app': typeof LocaleAppIndexRoute
  '/$locale/como-funciona': typeof LocaleComoFuncionaIndexRoute
  '/$locale/quero-ajudar': typeof LocaleQueroAjudarIndexRoute
  '/$locale/seja-um-parceiro': typeof LocaleSejaUmParceiroIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/app': typeof AppRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/app/': typeof LocaleAppIndexRoute
  '/$locale/como-funciona/': typeof LocaleComoFuncionaIndexRoute
  '/$locale/quero-ajudar/': typeof LocaleQueroAjudarIndexRoute
  '/$locale/seja-um-parceiro/': typeof LocaleSejaUmParceiroIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/app'
    | '/$locale/'
    | '/$locale/app/'
    | '/$locale/como-funciona/'
    | '/$locale/quero-ajudar/'
    | '/$locale/seja-um-parceiro/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/$locale'
    | '/$locale/app'
    | '/$locale/como-funciona'
    | '/$locale/quero-ajudar'
    | '/$locale/seja-um-parceiro'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/app'
    | '/$locale/'
    | '/$locale/app/'
    | '/$locale/como-funciona/'
    | '/$locale/quero-ajudar/'
    | '/$locale/seja-um-parceiro/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  AppRoute: typeof AppRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/seja-um-parceiro/': {
      id: '/$locale/seja-um-parceiro/'
      path: '/seja-um-parceiro'
      fullPath: '/$locale/seja-um-parceiro/'
      preLoaderRoute: typeof LocaleSejaUmParceiroIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/quero-ajudar/': {
      id: '/$locale/quero-ajudar/'
      path: '/quero-ajudar'
      fullPath: '/$locale/quero-ajudar/'
      preLoaderRoute: typeof LocaleQueroAjudarIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/como-funciona/': {
      id: '/$locale/como-funciona/'
      path: '/como-funciona'
      fullPath: '/$locale/como-funciona/'
      preLoaderRoute: typeof LocaleComoFuncionaIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/app/': {
      id: '/$locale/app/'
      path: '/app'
      fullPath: '/$locale/app/'
      preLoaderRoute: typeof LocaleAppIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleAppIndexRoute: typeof LocaleAppIndexRoute
  LocaleComoFuncionaIndexRoute: typeof LocaleComoFuncionaIndexRoute
  LocaleQueroAjudarIndexRoute: typeof LocaleQueroAjudarIndexRoute
  LocaleSejaUmParceiroIndexRoute: typeof LocaleSejaUmParceiroIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleAppIndexRoute: LocaleAppIndexRoute,
  LocaleComoFuncionaIndexRoute: LocaleComoFuncionaIndexRoute,
  LocaleQueroAjudarIndexRoute: LocaleQueroAjudarIndexRoute,
  LocaleSejaUmParceiroIndexRoute: LocaleSejaUmParceiroIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  AppRoute: AppRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
