/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotFoundIndexRouteImport } from './routes/not-found/index'
import { Route as LandingIndexRouteImport } from './routes/landing/index'
import { Route as AppHomeRouteImport } from './routes/app/home'
import { Route as AppHomeIndexRouteImport } from './routes/app/home/index'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundIndexRoute = NotFoundIndexRouteImport.update({
  id: '/not-found/',
  path: '/not-found/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/landing/',
  path: '/landing/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeIndexRoute = AppHomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppHomeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/home': typeof AppHomeRouteWithChildren
  '/landing/': typeof LandingIndexRoute
  '/not-found/': typeof NotFoundIndexRoute
  '/app/home/': typeof AppHomeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/landing': typeof LandingIndexRoute
  '/not-found': typeof NotFoundIndexRoute
  '/app/home': typeof AppHomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/home': typeof AppHomeRouteWithChildren
  '/landing/': typeof LandingIndexRoute
  '/not-found/': typeof NotFoundIndexRoute
  '/app/home/': typeof AppHomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/home'
    | '/landing/'
    | '/not-found/'
    | '/app/home/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app' | '/landing' | '/not-found' | '/app/home'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/home'
    | '/landing/'
    | '/not-found/'
    | '/app/home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LandingIndexRoute: typeof LandingIndexRoute
  NotFoundIndexRoute: typeof NotFoundIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found/': {
      id: '/not-found/'
      path: '/not-found'
      fullPath: '/not-found/'
      preLoaderRoute: typeof NotFoundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing/': {
      id: '/landing/'
      path: '/landing'
      fullPath: '/landing/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/home/': {
      id: '/app/home/'
      path: '/'
      fullPath: '/app/home/'
      preLoaderRoute: typeof AppHomeIndexRouteImport
      parentRoute: typeof AppHomeRoute
    }
  }
}

interface AppHomeRouteChildren {
  AppHomeIndexRoute: typeof AppHomeIndexRoute
}

const AppHomeRouteChildren: AppHomeRouteChildren = {
  AppHomeIndexRoute: AppHomeIndexRoute,
}

const AppHomeRouteWithChildren =
  AppHomeRoute._addFileChildren(AppHomeRouteChildren)

interface AppRouteChildren {
  AppHomeRoute: typeof AppHomeRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppHomeRoute: AppHomeRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LandingIndexRoute: LandingIndexRoute,
  NotFoundIndexRoute: NotFoundIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
